# File: .github/workflows/build_fivem_linux.yml
name: Build FiveM Linux Server and Release

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_release:
    name: Build and Release (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Initialize Submodules
        run: |
          git submodule update --init --recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang dotnet-sdk-6.0 unzip python3 python3-pip \
                                  libunwind-dev libc6-dev libcurl4-openssl-dev libssl-dev \
                                  zlib1g-dev libgflags-dev

      - name: Install Python Packages
        run: |
          pip3 install ply

      - name: Install Premake5
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
          tar -xvf premake-5.0.0-beta2-linux.tar.gz
          sudo mv premake5 /usr/local/bin

      - name: Generate Build Files with Premake
        run: |
          cd code
          premake5 gmake2 --game=server

      - name: Build Project with Verbose Output
        run: |
          cd code/build/server/linux
          make VERBOSE=1  # Enable verbose output to diagnose issues

      - name: Archive Build Output
        run: |
          cd code/build/server/linux
          tar -czf fivem-linux-server.tar.gz *

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}
          name: FiveM Linux Server Release v${{ github.run_number }}
          files: code/build/server/linux/fivem-linux-server.tar.gz
